### ISSUE TITLE
Unable to run `npx tws --live --query="developer"`

### ISSUE THREAD

**Issue by mrspence** [molebox/tweespaces#1]
Heya, really cool CLI idea! [Saw your tweet](https://twitter.com/studio_hungry/status/1430534221236424708) on it 😎

For some reason I can't run it in my own terminal (tried both PowerShell and Bash).

![image](https://user-images.githubusercontent.com/30320791/130820898-10aa44ff-d7d8-4d8a-b235-e7782fb51aaa.png)

Is there a setup step required?

My node version is v14.15.0

_I honestly suspect this might be an issue with my environment, though I have not had this issue before with npx commands..._

**Comment by molebox** [comment]
Hey @mrspence ! Thanks! 

Hmm, ive not idea why its not working, thats annoying... Im on node -v 14.15.1

![working-tweespaces](https://user-images.githubusercontent.com/22930449/130825998-8b62ae3e-a504-49c8-9c01-eb9a07e45a51.gif)

**Comment by molebox** [comment]
Hey @mrspence reporting back to say all is fixed now. The command to use is now `npx tweespaces`. Thanks for raising this!
